Ensures behaviors and triggers are detached when object unloads
microsoft/XamlBehaviorsWpf pull request #97
Opened 2021-10-21 17:38 UTC by pedrolamas

### Description of Change ###

If the object that is attached is a `FrameworkElement`, we will then monitor the `Loaded` and `Unloaded` events to attach and detach all triggers and behaviors accordingly.

### Bugs Fixed ###

Fixes #93 

### API Changes ###

N/A

### Behavioral Changes ###

If the object that is attached is a `FrameworkElement`, we will then monitor the `Loaded` and `Unloaded` events to attach and detach all triggers and behaviors accordingly.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [X] Rebased on top of master at time of PR
- [X] Changes adhere to coding standard

2021-10-21 17:43 UTC, brianlagunas requested changes

2021-10-21 17:43 UTC, brianlagunas commented on src/Microsoft.Xaml.Behaviors/Interaction.cs
> +                GetTriggers(d).Attach(d);
copy/paste bug :)

2021-10-21 17:43 UTC, brianlagunas commented on src/Microsoft.Xaml.Behaviors/Interaction.cs
> +                    frameworkElement.Loaded -= FrameworkElement_Loaded;
I'm not sure attaching is a real issue, and we need to verify this doesn't cause duplicate attachments

2021-10-21 18:16 UTC, pedrolamas commented on src/Microsoft.Xaml.Behaviors/Interaction.cs
> +                GetTriggers(d).Attach(d);
Oops... sorry, fixed now!

2021-10-21 18:17 UTC, pedrolamas commented on src/Microsoft.Xaml.Behaviors/Interaction.cs
> +                    frameworkElement.Loaded -= FrameworkElement_Loaded;
Very good point: it was necessary for the way that this works on UWP, but might not be required here... this needs more testing to confirm!

2021-10-21 18:21 UTC, pedrolamas commented on src/Microsoft.Xaml.Behaviors/Interaction.cs
> +                    frameworkElement.Loaded -= FrameworkElement_Loaded;
At first view, this should be a safe change considering that the collection does keep track if it is already attached or not (so it won't ask each behavior/trigger to attach if it has done so before)

2021-10-21 23:28 UTC, brianlagunas commented
I'm going to close this because I want to write some unit tests around this functionality, and experiment with various use-cases.

Thanks for the inspiration.

2021-10-21 23:28 UTC, closed without merging

2021-10-22 00:06 UTC, brianlagunas commented
@pedrolamas I'm also concerned about hooking this event

```
frameworkElement.Unloaded += FrameworkElement_Unloaded;
```

This seems to be a memory leak to me. Since we are hooking into the event from the attached property, but never unsubscribing from the event.